const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const GOOGLE_REDIRECT_URI = process.env.GOOGLE_REDIRECT_URI;
const FIREBASE_DB_URL = process.env.FIREBASE_DB_URL;

module.exports = {
	GOOGLE_CLIENT_SECRET,
	GOOGLE_CLIENT_ID,
	GOOGLE_REDIRECT_URI,
	FIREBASE_DB_URL
};
